---
- import_role:
    name: geerlingguy.php
  become: true
  become_user: root
- import_role:
    name: geerlingguy.composer
  become: true
  become_user: root
- import_role:
    name: geerlingguy.php-mysql
  become: true
  become_user: root
- import_role:
    name: geerlingguy.firewall
  become: true
  become_user: root

- import_role:
    name: geerlingguy.glusterfs
  become: true
  become_user: root


- name: Ensure Gluster brick and mount directories exist.
  become: true
  become_user: root
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Print variables
  debug:
    msg: "inventory is {{ inventory_hostname }} groups gluster is {{ gluster_cluster }}"

- name: Configure Gluster volume.
  become: true
  become_user: root
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    # replicas: 2
    cluster: "{{ gluster_cluster }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  become: true
  become_user: root
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted